### ISSUE TITLE
version-4.2 seems to be broken

### ISSUE THREAD

**Issue by lveyde** [kubevirt/machine-remediation-operator#57]
version-4.2 seems to be broken:

# github.com/kubevirt/hyperconverged-cluster-operator/vendor/kubevirt.io/machine-remediation-operator/pkg/operator/components
../../vendor/kubevirt.io/machine-remediation-operator/pkg/operator/components/csv.go:120:4: cannot use *"github.com/kubevirt/hyperconverged-cluster-operator/vendor/github.com/coreos/go-semver/semver".New(data.CSVVersion) (type "github.com/kubevirt/hyperconverged-cluster-operator/vendor/github.com/coreos/go-semver/semver".Version) as type version.OperatorVersion in field value

**Comment by rthallisey** [comment]
cc @beekhof
